apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lumina

labels:
  - pairs:
      app.kubernetes.io/part-of: lumina-sql-agent

resources:
  - namespace.yaml
  - config.yaml
  - postgres.yaml
  - redis.yaml
  - api.yaml

images:
  - name: lumina-sql-agent
    newTag: local
